variable "env" {}
variable "vpc_name" {}
variable "cidr_block" {}
variable "igw_name" {}
variable "application-subnet-cidr-block" {}
variable "subnet1-name" {}
variable "public-subnet-rt-name" {}
variable "sg-name" {}
variable "instance_size" {}
variable "key_pair_name" {}
variable "instance_name" {}
variable "bucket_name" {}
variable "db-subnet1-cidr-block" {}
variable "db-subnet2-cidr-block" {}
variable "subnet2-name" {}
variable "subnet3-name" {}
variable "db-instance-size" {}
variable "subnet-group-name" {}
variable "db-sg-name" {}
variable "rds-username" {}
variable "rds-pwd" {}
variable "db-name" {}
variable "rds-name" {}
variable "role-name" {}
variable "policy-name" {}
variable "instance-profile-name" {}