variable "env" {}
variable "vpc_name" {}
variable "cidr_block" {}
variable "igw_name" {}
variable "application_subnet_cidr_block" {}
variable "subnet1_name" {}
variable "public_subnet_rt_name" {}
variable "sg_name" {}
variable "instance_size" {}
variable "key_pair_name" {}
variable "volume_size" {}
variable "instance_name" {}
variable "bucket_name" {}
variable "db_subnet1_cidr_block" {}
variable "db_subnet2_cidr_block" {}
variable "subnet2_name" {}
variable "subnet3_name" {}
variable "db_instance_size" {}
variable "subnet_group_name" {}
variable "db_sg_name" {}
variable "rds_username" {}
variable "rds_pwd" {}
variable "db_name" {}
variable "rds_name" {}
variable "allocated_storage" {}
variable "storage_encrypted" {}
variable "deletion_protection" {}
variable "publicly_accessible" {}
variable "multi_az" {}
variable "retention_period" {}
variable "role_name" {}
variable "policy_name" {}
variable "instance_profile_name" {}